# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0002_auto_20170505_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_detallearticulo',
            name='localizacion',
        ),
        migrations.AddField(
            model_name='tb_detallearticulo',
            name='estante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tb_detallearticulo',
            name='nivel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tb_articulo',
            name='existencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='tb_Localizacion',
        ),
    ]
