# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0004_tb_entrada_tb_incidenciaarticulo_tb_salida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_entrada',
            name='cod_det_art',
        ),
        migrations.RemoveField(
            model_name='tb_salida',
            name='cod_det_art',
        ),
        migrations.AddField(
            model_name='tb_entrada',
            name='cod_art',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Articulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tb_entrada',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tb_salida',
            name='cod_art',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Articulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tb_salida',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
