# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0005_auto_20170506_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_entrada',
            name='cod_art',
        ),
        migrations.RemoveField(
            model_name='tb_salida',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='tb_salida',
            name='cod_art',
        ),
        migrations.RemoveField(
            model_name='tb_salida',
            name='departamento',
        ),
        migrations.DeleteModel(
            name='tb_entrada',
        ),
        migrations.DeleteModel(
            name='tb_salida',
        ),
    ]
