# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0008_auto_20170507_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_salida',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='tb_salida',
            name='cod_art',
        ),
        migrations.RemoveField(
            model_name='tb_salida',
            name='departamento',
        ),
        migrations.DeleteModel(
            name='tb_salida',
        ),
    ]
