# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0009_auto_20170513_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro_salida', models.DateField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=20, null=True)),
                ('personal_entregado', models.CharField(blank=True, max_length=60, null=True)),
                ('usuario_regis', models.CharField(blank=True, max_length=20, null=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.Agencia')),
                ('cod_det_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_DetalleArticulo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Jefatura')),
            ],
        ),
    ]
