# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventariohonducorapp', '0011_auto_20170516_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_agencia', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('telefono1', models.CharField(max_length=40)),
                ('telefono2', models.CharField(max_length=40)),
                ('telefono3', models.CharField(max_length=40)),
                ('imagen', models.FileField(upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='tb_Admin_Inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tb_Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_art', models.CharField(max_length=50)),
                ('descrip', models.TextField(blank=True, null=True)),
                ('imagen_art', models.FileField(blank=True, null=True, upload_to='imagenes/')),
                ('existencia', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tb_categoria_art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cat', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tb_CategoriaMobiliario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=40)),
                ('descripccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tb_Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_depart', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='tb_DetalleArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_unitario', models.FloatField(blank=True, null=True)),
                ('garantia', models.CharField(blank=True, max_length=60, null=True)),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('unidades', models.IntegerField(blank=True, null=True)),
                ('nivel', models.CharField(blank=True, max_length=50, null=True)),
                ('estante', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Articulo')),
            ],
        ),
        migrations.CreateModel(
            name='tb_Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(blank=True, max_length=20, null=True)),
                ('id_empleado', models.CharField(max_length=20)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('tel1', models.CharField(blank=True, max_length=20, null=True)),
                ('tel2', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado_emp', models.CharField(blank=True, max_length=30, null=True)),
                ('foto', models.ImageField(upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='tb_entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro_entrada', models.DateField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario_regis', models.CharField(blank=True, max_length=20, null=True)),
                ('cod_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Articulo')),
            ],
        ),
        migrations.CreateModel(
            name='tb_incidenciaArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripccion_incAr', models.TextField(blank=True, null=True)),
                ('cod_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Articulo')),
            ],
        ),
        migrations.CreateModel(
            name='tb_incidenciaMobiliario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidencia', models.CharField(max_length=40)),
                ('descripccion', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='tb_incidenciaVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidencia', models.CharField(max_length=40)),
                ('descripccion', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='tb_Inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(blank=True, max_length=40, null=True)),
                ('destino_actual', models.CharField(blank=True, max_length=70, null=True)),
                ('numero_instrumento', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_otorgamiento', models.DateField(blank=True, null=True)),
                ('notario_otorgante', models.CharField(blank=True, max_length=80, null=True)),
                ('valor_adq', models.FloatField(blank=True, null=True)),
                ('forma_adquisicion', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_acuerdo', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('num_registro_propiedad', models.CharField(blank=True, max_length=60, null=True)),
                ('folio_registro_propiedad', models.CharField(blank=True, max_length=60, null=True)),
                ('tomo_registro_propiedad', models.CharField(blank=True, max_length=60, null=True)),
                ('num_catastro', models.CharField(blank=True, max_length=40, null=True)),
                ('nombre_encargado', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tb_Jefatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jefatura', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='tb_Mobiliario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(blank=True, max_length=40, null=True)),
                ('serie', models.CharField(blank=True, max_length=40, null=True)),
                ('color', models.CharField(blank=True, max_length=40, null=True)),
                ('estado', models.CharField(blank=True, max_length=40, null=True)),
                ('cod_inventario', models.CharField(max_length=40)),
                ('observacion', models.CharField(blank=True, max_length=40, null=True)),
                ('costo_uni', models.FloatField(blank=True, null=True)),
                ('descripccion', models.TextField(blank=True, null=True)),
                ('anio_modelo', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('cod_cat_mobiliario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_CategoriaMobiliario')),
            ],
        ),
        migrations.CreateModel(
            name='tb_MobiliarioDevuelto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField()),
                ('estado', models.CharField(max_length=40)),
                ('descripccion', models.TextField(blank=True, null=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='imagenes/')),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Empleado')),
                ('cod_mobiliario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Mobiliario')),
            ],
        ),
        migrations.CreateModel(
            name='tb_MobiliarioPrestado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestado', models.DateField()),
                ('estado', models.CharField(blank=True, max_length=40, null=True)),
                ('descripccion', models.TextField(blank=True, null=True)),
                ('gerencia', models.CharField(blank=True, max_length=40, null=True)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('levanto_inventario', models.CharField(blank=True, max_length=70, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Empleado')),
                ('cod_mobiliario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Mobiliario')),
            ],
        ),
        migrations.CreateModel(
            name='tb_Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_municipio', models.CharField(max_length=50)),
                ('cod_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='tb_salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro_salida', models.DateField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=20, null=True)),
                ('personal_entregado', models.CharField(blank=True, max_length=60, null=True)),
                ('usuario_regis', models.CharField(blank=True, max_length=20, null=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.Agencia')),
                ('cod_det_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_DetalleArticulo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Jefatura')),
            ],
        ),
        migrations.CreateModel(
            name='tb_Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('serie_motor', models.CharField(blank=True, max_length=50, null=True)),
                ('placa', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('anio_modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('costo', models.FloatField(blank=True, null=True)),
                ('descripccion', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cod_inventario', models.CharField(max_length=50)),
                ('imagen_vehi', models.FileField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='tb_VehiculoAsignado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField()),
                ('estado', models.CharField(max_length=40)),
                ('descripccion', models.TextField(blank=True, null=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='imagenes/')),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Empleado')),
                ('cod_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='tb_incidenciavehiculo',
            name='cod_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Vehiculo'),
        ),
        migrations.AddField(
            model_name='tb_incidenciamobiliario',
            name='cod_mobiliario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Mobiliario'),
        ),
        migrations.AddField(
            model_name='tb_articulo',
            name='cod_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_categoria_art'),
        ),
        migrations.AddField(
            model_name='tb_admin_inmueble',
            name='cod_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Empleado'),
        ),
        migrations.AddField(
            model_name='tb_admin_inmueble',
            name='cod_inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Inmueble'),
        ),
        migrations.AddField(
            model_name='agencia',
            name='tb_Municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Municipio'),
        ),
    ]
