# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0012_auto_20170516_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_incidenciaarticulo',
            old_name='descripccion_incAr',
            new_name='condicion',
        ),
        migrations.RemoveField(
            model_name='tb_incidenciaarticulo',
            name='cod_art',
        ),
        migrations.AddField(
            model_name='tb_incidenciaarticulo',
            name='cod_det_art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_DetalleArticulo'),
        ),
        migrations.AddField(
            model_name='tb_incidenciaarticulo',
            name='descripccion_inc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tb_incidenciaarticulo',
            name='estado',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='tb_incidenciaarticulo',
            name='fecha_registro_inc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='telefono1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='telefono2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='telefono3',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
