# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0014_auto_20170602_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_VehiculoDescargado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=40, null=True)),
                ('descripccion', models.TextField(blank=True, null=True)),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Empleado')),
                ('cod_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Vehiculo')),
            ],
        ),
    ]
