# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0015_tb_vehiculodescargado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_vehiculoasignado',
            name='cod_empleado',
        ),
        migrations.RemoveField(
            model_name='tb_vehiculoasignado',
            name='cod_vehiculo',
        ),
        migrations.DeleteModel(
            name='tb_VehiculoAsignado',
        ),
    ]
