# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0016_auto_20170605_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_VehiculoAsignado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('estado', models.CharField(max_length=40)),
                ('descripccion', models.TextField(blank=True, null=True)),
                ('agencia', models.CharField(max_length=50)),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Empleado')),
                ('cod_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Vehiculo')),
            ],
        ),
    ]
