# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0018_tb_inmueble_otorgante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_inmueble',
            name='nombre_encargado',
        ),
    ]
