# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0019_remove_tb_inmueble_nombre_encargado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_mobiliariodevuelto',
            name='imagen',
        ),
    ]
