# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0020_remove_tb_mobiliariodevuelto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_detallearticulo',
            name='usuario_regis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
