# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0021_tb_detallearticulo_usuario_regis'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='estado_agencia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tb_categoriamobiliario',
            name='estado_cat_mobi',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tb_departamento',
            name='estado_dep',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tb_mobiliario',
            name='estado_mobiliario',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tb_municipio',
            name='estado_muni',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
