# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0023_auto_20170608_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_departamento',
            name='usuario_regis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
