# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0025_auto_20170609_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_mobiliario',
            name='ubicacion_actual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
