# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0026_tb_mobiliario_ubicacion_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_inmueble',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tb_inmueble',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
