# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0028_auto_20170609_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_admin_inmueble',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
