# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0030_tb_clasificacion_estados_tb_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_InmuebleDescargado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=40, null=True)),
                ('descripccion', models.TextField(blank=True, null=True)),
                ('estado_inmueble_des', models.CharField(blank=True, max_length=30, null=True)),
                ('usuario_regis', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Empleado')),
                ('cod_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Inmueble')),
            ],
        ),
    ]
