# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0031_tb_inmuebledescargado'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_audit_det_articulo',
            fields=[
                ('pk_audit_det_articulo', models.IntegerField(primary_key=True, serialize=False)),
                ('TableName', models.CharField(max_length=45)),
                ('Operation', models.CharField(max_length=1)),
                ('OldValue', models.TextField(blank=True, null=True)),
                ('NewValue', models.TextField(blank=True, null=True)),
                ('UpdateDate', models.DateField()),
                ('UserName', models.CharField(max_length=45)),
            ],
        ),
    ]
