# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0032_tb_audit_det_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_audit_det_articulo',
            name='pk_audit_det_articulo',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
