# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0033_auto_20170610_0014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tb_audit_det_articulo',
        ),
    ]
