# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0036_tb_audit_det_vehiculo_tb_audit_entrada_tb_audit_mobiliario_tb_audit_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_detalle_salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro_salida', models.DateField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=20, null=True)),
                ('personal_entregado', models.CharField(blank=True, max_length=60, null=True)),
                ('usuario_regis', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_salida', models.CharField(blank=True, max_length=30, null=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.Agencia')),
                ('cod_det_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_DetalleArticulo')),
            ],
        ),
        migrations.RemoveField(
            model_name='tb_salida',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='tb_salida',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='tb_salida',
            name='cod_det_art',
        ),
        migrations.RemoveField(
            model_name='tb_salida',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='tb_salida',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='tb_salida',
            name='estado_salida',
        ),
        migrations.RemoveField(
            model_name='tb_salida',
            name='personal_entregado',
        ),
        migrations.AddField(
            model_name='tb_detalle_salida',
            name='cod_salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_salida'),
        ),
        migrations.AddField(
            model_name='tb_detalle_salida',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Jefatura'),
        ),
    ]
