# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0037_auto_20170611_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_detalle_salida',
            name='agencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tb_detalle_salida',
            name='departamento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
