# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0038_auto_20170612_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_audit_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operation', models.CharField(max_length=1)),
                ('UpdateDate', models.DateField()),
                ('UserName', models.CharField(max_length=45)),
            ],
        ),
    ]
