# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0039_tb_audit_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_mobiliario_prestado_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gerencia', models.CharField(blank=True, max_length=40, null=True)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateField()),
                ('usuario_regis', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Empleado')),
                ('cod_mobiliario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariohonducorapp.tb_Mobiliario')),
            ],
        ),
    ]
