# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0040_tb_mobiliario_prestado_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_mobiliario_prestado_detalle',
            name='cod_empleado',
        ),
        migrations.RemoveField(
            model_name='tb_mobiliario_prestado_detalle',
            name='cod_mobiliario',
        ),
        migrations.DeleteModel(
            name='tb_mobiliario_prestado_detalle',
        ),
    ]
