# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0044_tb_proveedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tb_proveedor',
        ),
    ]
