# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0045_delete_tb_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('rtn', models.CharField(blank=True, max_length=50, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=50, null=True)),
                ('representante_legar', models.CharField(blank=True, max_length=60, null=True)),
                ('ciudad', models.CharField(max_length=30)),
                ('telefono1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pais', models.CharField(max_length=40)),
                ('sitio_web', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
