# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0046_tb_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_proveedor',
            old_name='representante_legar',
            new_name='representante_legal',
        ),
    ]
