# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0047_auto_20170620_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_proveedor',
            name='personal_contacto',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
