# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0048_tb_proveedor_personal_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_proveedor',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
