# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0049_tb_proveedor_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_incidenciaarticulo',
            name='condicion',
        ),
        migrations.RemoveField(
            model_name='tb_incidenciaarticulo',
            name='estado',
        ),
    ]
