# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohonducorapp', '0050_auto_20170620_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_empleado',
            name='puesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
